# Generated by Django 5.2.2 on 2025-06-11 13:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_product_slup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slup',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
